package com.example.service

import android.app.Notification
import android.content.pm.PackageManager
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import com.example.model.NotificationPayload
import com.example.util.CrashProtector
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow

class UbaidNotificationListenerService : NotificationListenerService() {
    private val TAG = "UbaidNotificationListener"

    override fun onListenerConnected() {
        super.onListenerConnected()
        instance = this
        _isServiceActive.value = true
        Log.d(TAG, "Ubaid Notification Listener connected.")
    }

    override fun onListenerDisconnected() {
        super.onListenerDisconnected()
        if (instance == this) {
            instance = null
            _isServiceActive.value = false
        }
        Log.w(TAG, "Ubaid Notification Listener disconnected.")
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        super.onNotificationPosted(sbn)
        if (sbn == null) return

        CrashProtector.safeRun(TAG, Unit) {
            // Ignore notifications generated by this app itself
            if (sbn.packageName == packageName) return@safeRun

            val extras = sbn.notification.extras ?: return@safeRun
            val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString() ?: ""
            val text = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString() ?: ""

            // Skip empty notifications
            if (title.isBlank() && text.isBlank()) return@safeRun

            val appName = try {
                packageManager.getApplicationLabel(
                    packageManager.getApplicationInfo(sbn.packageName, 0)
                ).toString()
            } catch (e: Exception) {
                sbn.packageName
            }

            val payload = NotificationPayload(
                key = sbn.key ?: "${sbn.packageName}_${sbn.id}",
                packageName = sbn.packageName,
                appName = appName,
                title = title,
                text = text,
                postTime = sbn.postTime,
                isRemoved = false
            )

            _notificationEvents.tryEmit(payload)
        }
    }

    override fun onNotificationRemoved(sbn: StatusBarNotification?) {
        super.onNotificationRemoved(sbn)
        if (sbn == null || sbn.packageName == packageName) return

        CrashProtector.safeRun(TAG, Unit) {
            val payload = NotificationPayload(
                key = sbn.key ?: "${sbn.packageName}_${sbn.id}",
                packageName = sbn.packageName,
                appName = sbn.packageName,
                title = "",
                text = "",
                postTime = System.currentTimeMillis(),
                isRemoved = true
            )
            _notificationEvents.tryEmit(payload)
        }
    }

    companion object {
        @Volatile
        var instance: UbaidNotificationListenerService? = null
            private set

        private val _isServiceActive = MutableStateFlow(false)
        val isServiceActive: StateFlow<Boolean> = _isServiceActive.asStateFlow()

        private val _notificationEvents = MutableSharedFlow<NotificationPayload>(extraBufferCapacity = 64)
        val notificationEvents: SharedFlow<NotificationPayload> = _notificationEvents.asSharedFlow()
    }
}
